POST http://localhost:8000/app/signup
Content-Type: application/json

{
    "name": "neha",
    "email":"neha@gmail.com",
    "phone": 9898756328,
    "work": "student",
    "password":"neha",
    "cpassword":"neha"
}